language: php

php:
  - 5.3
  # - 5.4

env:
  - SYMFONY_VERSION=origin/master

before_script:
  - composer install --dev

script: phpunit

notifications:
    webhooks: http://sonata-project.org/bundles/admin/master/travis
