language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  fast_finish: true
  include:
    - php: 5.3.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.6.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 5.6
      env: SYMFONY_VERSION="3.0.x-dev as 2.8"
  allow_failures:
    - php: 7.0
    - php: hhvm
    - env: SYMFONY_VERSION=2.8.*@dev
    - env: SYMFONY_VERSION="3.0.x-dev as 2.8"

before_script:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" = "2.8.*@dev" ] || [ "$SYMFONY_VERSION" = "3.0.x-dev as 2.8" ]; then SYMFONY_DEPRECATIONS_HELPER=strict; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer update --prefer-source --no-interaction $COMPOSER_FLAGS
  - sudo pip install -r Resources/doc/requirements.txt

script: make test

notifications:
    webhooks: https://sonata-project.org/bundles/admin/master/travis
