language: php
php:
  - 5.3
  # - 5.4
  
env:
  - SYMFONY_VERSION=v2.0.0
  - SYMFONY_VERSION=v2.0.1
  # - SYMFONY_VERSION=v2.0.2 # broken tag
  - SYMFONY_VERSION=v2.0.3
  - SYMFONY_VERSION=v2.0.4
  - SYMFONY_VERSION=v2.0.5
  - SYMFONY_VERSION=origin/master

before_script: php Tests/tests/vendors.php
script: phpunit