name: Frontend

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    webpack-encore:
        name: Webpack Encore

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Node 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install NPM dependencies
              uses: bahmutov/npm-install@v1

            - name: Run Eslint
              run: yarn run eslint assets/js

            - name: Run Stylelint
              run: yarn run stylelint assets/scss

            - name: Run Webpack Encore
              run: yarn encore production
